import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Loique Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
          <section className='min-h-screen'>
              {/*nav section*/}
              <nav className='py-10 mb-12 flex justify-between '>
                <h1 className='text-xl font-burtons'>jscoderdelypou</h1>
                <ul className='flex items-center'>
                  <BsFillMoonStarsFill onClick={( ) => setDarkMode(!darkMode)} className='cursor-pointer text-2xl' />
                  <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
                </ul>
              </nav>

              {/*Description section*/}
              <div className='text-center p-10 dark: text-white'>
                <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl  '>Loique Fogouang</h2>
                <h3 className='text-2xl py-2 md:text-3xl'>Devloper and Designer</h3>
                <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto'>Freelancer providing servies for programming needs. Join me down below  and let's get craking!!!</p>
              </div>

              <div className='text-5xl flex justify-center gap-16 py-6 text-gray-600 '>
                <AiFillTwitterCircle />
                <AiFillLinkedin />
                <AiFillYoutube />
              </div>

              <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96'>
                <Image src={deved} layout="fill" objectFit='cover' />
              </div>
          </section>

          {/*Body section*/}
          <section>
            <div >
              <h3 className='text-3xl py-1  dark: text-white'>Services I offer</h3>
              <p className='text-md leading-8 text-gray-800'> Since the beginning of my journey as a 
                freelancer developer and designer, i have done remote work for  
                <span className='text-teal-500'> agencies </span> consulted for
                 <span className='text-teal-500'> startups </span> 
                and collaborated with talented peaople to create digital products for both business and consumer use.
              </p>
              <p className='text-md leading-8 text-gray-800'> I offer from a wide range of services, including programming and teaching</p>
            </div>

            {/*card system*/}
            <div className='lg:flex gap-10'>
              <div className='text-center flex flex-col justify-center items-center shadow-lg p-10 rounded-xl my-10 atems-center  dark:bg-white'>
                <Image src={design} width={100} height={100} />
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designes</h3>
                <p className='py-2'>Creating elegant designs suited for your your needs fellowing design theory</p>
                <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Illustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
              </div>

              <div className='text-center flex flex-col justify-center items-center shadow-lg p-10 rounded-xl my-10 atems-center  dark:bg-white'>
                <Image src={code} width={100} height={100} />
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designes</h3>
                <p className='py-2'>Creating elegant designs suited for your your needs fellowing design theory</p>
                <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Illustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
              </div>

              <div className='text-center flex flex-col justify-center items-center shadow-lg p-10 rounded-xl my-10 atems-center  dark:bg-white'>
                <Image src={consulting} width={100} height={100} />
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designes</h3>
                <p className='py-2'>Creating elegant designs suited for your your needs fellowing design theory</p>
                <h4 className='py-4 text-teal-600'>Design tools I use</h4>
                <p className="text-gray-800 py-1">Photoshop</p>
                <p className="text-gray-800 py-1">Illustrator</p>
                <p className="text-gray-800 py-1">Figma</p>
              </div>
            </div>
          </section>
          {/*porfolio section*/}
          <section>
              <div className='text-3xl py-1 dark: text-white'>
                <h3>Portfolio</h3>
              </div>
              <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
                <div  className='basis-1/3 flex-1'>
                  <Image src={web1} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />
                </div>

                <div className='basis-1/3 flex-1'>
                  <Image src={web2} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive"  />
                </div>

                <div className='basis-1/3 flex-1'>
                  <Image src={web3} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />
                </div>

                <div className='basis-1/3 flex-1'>
                  <Image src={web4} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />
                </div>

                <div className='basis-1/3 flex-1'>
                  <Image src={web5} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />
                </div>

                <div className='basis-1/3 flex-1'>
                  <Image src={web6} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />
                </div>
              </div>
          </section>
      </main>
    </div>
  )
}
